[package]
name = "jvm-r"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.4.1"
byteorder = "1.5.0"
num_enum = "0.7.0"